import Head from 'next/head'
import React,{createContext, useState} from 'react'
import styles from '../styles/Home.module.css'
import Speakers from '../components/Speakers/Speakers'
import LeftPanel from '../components/LeftPanel/LeftPanel'
import MainPanel from '../components/MainPanel/MainPanel'
import RightPanel from '../components/RightPanel/RightPanel'
import Nav from '../components/Nav/Nav'







export default function Home() {
  const [expand,setExpand]=useState(false)

  const [textExpander, setTextExpander] = useState({
      shortword:"",
      longword:""
  })
  const [storeexpanders,setStoreexpanders]=useState([])

  const [transcript,setTranscript]=useState()
  
  const [darktheme,setDarkTheme]=useState(true)

 

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



<Nav transcript={transcript} darktheme={darktheme} setDarkTheme={setDarkTheme}/>
      <div className={styles.flex}>
        
      <LeftPanel  expand={expand} setExpand={setExpand}
         textExpander={textExpander} setTextExpander={setTextExpander} 
         storeexpanders={storeexpanders} setStoreexpanders={setStoreexpanders}/>
      <MainPanel expand={expand} setExpand={setExpand} transcript={transcript} setTranscript={setTranscript}
         textExpander={textExpander} setTextExpander={setTextExpander} 
         storeexpanders={storeexpanders} setStoreexpanders={setStoreexpanders}/>
      <RightPanel expand={expand} setExpand={setExpand}
         textExpander={textExpander} setTextExpander={setTextExpander} 
         storeexpanders={storeexpanders} setStoreexpanders={setStoreexpanders}/>
      </div>

    </div>
    
   
  )
}
